# Generated by Django 5.0.6 on 2024-07-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0003_questionmetadata_alter_appearance_meta_and_more'),
        ('tests', '0003_alter_testquestion_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionMeta',
        ),
    ]
