# Generated by Django 5.0.6 on 2024-07-17 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0005_university_alter_question_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='admission_test',
        ),
        migrations.AddField(
            model_name='appearance',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qb.university'),
        ),
    ]
