# Generated by Django 5.0.6 on 2024-07-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0006_remove_appearance_admission_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='meta',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='meta',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='meta',
            new_name='metadata',
        ),
    ]
