# Generated by Django 5.0.6 on 2024-07-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question_quantity',
            field=models.BigIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='test',
            name='test_length_minute',
            field=models.BigIntegerField(default=12),
        ),
    ]
