# Generated by Django 5.0.6 on 2024-07-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0003_questionmetadata_alter_appearance_meta_and_more'),
        ('tests', '0002_test_question_quantity_test_test_length_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qb.questionmetadata'),
        ),
    ]
