# Generated by Django 5.0.6 on 2024-07-17 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_marking_criterion_alter_markingcriterion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='tests.testquestion'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test'),
        ),
    ]
